services:
  postgres:
    image: postgres:15-alpine
    container_name: fs-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - feedback-system-network

  backend:
    container_name: fs-backend-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@fs-postgres:${DB_PORT}/${DB_NAME}?schema=public
    env_file:
      - .env
    networks:
      - feedback-system-network

  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - '2510:80'
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - feedback-system-network

volumes:
  pg_data:

networks:
  feedback-system-network:
    external: true
