server {
    listen 2510; # Внешний порт, который слушает Nginx

    # 1. Маршрут для Frontend 1 (localhost:2510/)
    # Используем 'location = /' для точного совпадения корневого пути
    location = / {
        proxy_pass http://frontend-f-table; 
        
        # Обязательные заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 2. Маршрут для Frontend 2 (localhost:2510/send)
    # Используем 'location /send' для маршрутизации с сохранением пути
    location = /send {
        # Запрос localhost:2510/send будет перенаправлен на http://localhost:3002/send
        proxy_pass http://frontend-f-form;
        
        # Обязательные заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 3. Маршрут для NestJS Backend (localhost:2510/api)
    # Используем 'location /api/' и proxy_pass без слэша в конце.
    location = /api {
        # Это КЛЮЧЕВОЙ МОМЕНТ для сохранения префикса.
        # Nginx перенаправит localhost:2510/api/feedback на http://localhost:3000/api/feedback
        proxy_pass http://nestjs-backend-f;
        
        # Обязательные заголовки
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}