server {
    listen 80;

    location = /send {
        return 301 $scheme://$http_host/send/;
    }

    location /send/ {
        proxy_pass http://fs-form-container:80/;
    }

    location /api {
        proxy_pass http://fs-backend-container:3000;
    }

    location / {
        proxy_pass http://fs-table-container:80;
    }
}